---
name: Linux GCC

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '17 */4 * * *'  # 17 min past every four hours.

env:
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONFIG_URL: https://github.com/sintef-ocean/conan-configs.git
  DEBIAN_FRONTEND: noninteractive
  TZ: Etc/UTC

jobs:
  conan-with-gcc:
    name: Conan
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        chain: ["chain1", "chain2", "chain3", "chain4"]
        profile: [gcc]
        compiler_version: [12, 14]
        include:
          - linux: debian:latest
          -
            linux: debian:trixie
            compiler_version: 14
          -
            linux: debian:bookworm
            compiler_version: 12
        exclude:
          - compiler_version: 14
            chain: chain1


    container:
      image: ${{ matrix.linux }}
      options: -u 0
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y jq pipx build-essential cmake git pkg-config
          pipx install conan
          echo "/github/home/.local/bin" >> $GITHUB_PATH
      - name: Conan configs
        run: |
          conan remote add sintef ${{ env.CONAN_UPLOAD }}
          git config --global --add safe.directory '*'
          conan config install ${{ env.CONFIG_URL }}  --type git -sf conan2.0
          conan config install ${{ env.CONFIG_URL }}  --type git -sf profiles -tf profiles
      - name: Conan install and build missing
        run: |
          conan install -s build_type=${{ matrix.build_type }} -s:b build_type=${{ matrix.build_type }} \
            -s compiler.version=${{ matrix.compiler_version }} -s:b compiler.version=${{ matrix.compiler_version }} \
            -pr:b=${{ matrix.profile }} -pr:h=${{ matrix.profile }} \
            -s:h hdf5/*:compiler.version=12 `
            -s:b hdf5/*:compiler.version=12 `
            -s:h netcdf/*:compiler.version=12 `
            -s:b netcdf/*:compiler.version=12 `
            -b missing:* -b outdated \
            -u --format=json ${{ matrix.chain }} > install.json
      - name: Conan upload
        run: |
          conan list --graph=install.json --graph-binaries=build --format=json > pkglist.json
          conan upload --confirm -r sintef --force -l pkglist.json || true
