---
name: Windows MSVC

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '17 */4 * * *'  # 17 min past every four hours.

env:
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONFIG_URL: https://github.com/sintef-ocean/conan-configs.git

jobs:
  conan-with-msvc:
    name: Conan
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        chain: ["chain1", "chain2", "chain3", "chain4"]
        profile: [msvc17]
        compiler_version: [192, 194]
        exclude:
          - chain: chain3
            compiler_version: 194
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade conan~=2.0
      - name: Configure Conan
        run: |
          conan remote add sintef ${{ env.CONAN_UPLOAD }}
          conan config install ${{ env.CONFIG_URL }}  --type git -sf conan2.0
          conan config install ${{ env.CONFIG_URL }}  --type git -sf profiles -tf profiles
      - name: Conan install and build missing
        run: |
          conan install -s build_type=${{ matrix.build_type }} -s:b build_type=${{ matrix.build_type }} `
            -s compiler.version=${{ matrix.compiler_version }} -s:b compiler.version=${{ matrix.compiler_version }} `
            -o tinyxml/*:shared=False `
            -s:h xapian-core/*:compiler.cppstd=14 `
            -s:b xapian-core/*:compiler.cppstd=14 `
            -pr:b=${{ matrix.profile }} -pr:h=${{ matrix.profile }} `
            -b missing:* -b outdated `
            -u --format=json ${{ matrix.chain }} > install.json
      - name: Conan upload
        shell: pwsh
        run: |
          conan list --graph=install.json --graph-binaries=build --format=json > pkglist.json
          conan upload --confirm -r sintef --force -l pkglist.json || true
