---
name: Windows MSVC

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '17 */2 * * *'  # 17 min past every two hours.

env:
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONFIG_URL: https://github.com/sintef-ocean/conan-configs.git

jobs:
  conan-with-msvc:
    name: Conan
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        conan: ["2.0"]
        build_type: [Debug, Release]
        chain: ["chain3"]
        profile: [msvc17]
        compiler_version: [192, 193]
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade conan~=${{ matrix.conan }}
      - name: Configure Conan
        run: conan remote add sintef ${{ env.CONAN_UPLOAD }}
      - name: Conan install and build missing
        run: |
          conan config install ${{ env.CONFIG_URL }}  --type git -sf conan${{ matrix.conan }}
          conan config install ${{ env.CONFIG_URL }}  --type git -sf profiles -tf profiles
          conan install -s build_type=${{ matrix.build_type }} `
            -s compiler.version=${{ matrix.compiler_version }} `
            -pr:b=${{ matrix.profile }} -pr:h=${{ matrix.profile }} `
            -b missing -b outdated -u --format=json ${{ matrix.chain }} > install.json
      - name: Conan upload
        shell: pwsh
        run: |
          conan list --graph=install.json --graph-binaries=build --format=json > pkglist.json
          conan upload --confirm -r sintef --force -l pkglist.json || true
